// <auto-generated />
using System;
using BibliotecaDados.Contexto;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace BibliotecaDados.Migrations
{
    [DbContext(typeof(BibliotecaContext))]
    partial class BibliotecaContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.2.6-servicing-10079")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("BibliotecaDominio.Entidades.Endereco", b =>
                {
                    b.Property<int>("EnderecoId")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Bairro");

                    b.Property<string>("CEP");

                    b.Property<string>("Complemento");

                    b.Property<string>("Logradouro");

                    b.Property<int?>("MunicipioId");

                    b.Property<int>("NumeroResidencial");

                    b.HasKey("EnderecoId");

                    b.HasIndex("MunicipioId");

                    b.ToTable("Enderecos");
                });

            modelBuilder.Entity("BibliotecaDominio.Entidades.ExemplarLivro", b =>
                {
                    b.Property<int>("ExemplarLivroId")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int?>("LivroId");

                    b.Property<int>("NumeroExemplar");

                    b.Property<string>("Registro");

                    b.HasKey("ExemplarLivroId");

                    b.HasIndex("LivroId");

                    b.ToTable("Exemplares");
                });

            modelBuilder.Entity("BibliotecaDominio.Entidades.Livro", b =>
                {
                    b.Property<int>("LivroId")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int?>("AssuntoId");

                    b.Property<int?>("AutorId");

                    b.Property<int?>("ClassificacaoId");

                    b.Property<int?>("EditoraId");

                    b.Property<string>("Titulo");

                    b.HasKey("LivroId");

                    b.HasIndex("AssuntoId");

                    b.HasIndex("AutorId");

                    b.HasIndex("ClassificacaoId");

                    b.HasIndex("EditoraId");

                    b.ToTable("Livros");
                });

            modelBuilder.Entity("BibliotecaDominio.Entidades.Pessoa", b =>
                {
                    b.Property<int>("PessoaId")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Cpf");

                    b.Property<DateTime>("DataDeNascimento");

                    b.Property<string>("Email");

                    b.Property<int?>("EnderecoId");

                    b.Property<int>("Idade");

                    b.Property<int?>("LoginDadosLoginId");

                    b.Property<string>("Nome");

                    b.Property<string>("Profissao");

                    b.Property<string>("RG");

                    b.Property<string>("Telefone");

                    b.HasKey("PessoaId");

                    b.HasIndex("Cpf");

                    b.HasIndex("EnderecoId");

                    b.HasIndex("LoginDadosLoginId");

                    b.ToTable("Pessoas");
                });

            modelBuilder.Entity("BibliotecaDominio.ObjetosValor.Assunto", b =>
                {
                    b.Property<int>("AssuntoId")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("AssuntoObra")
                        .IsRequired();

                    b.HasKey("AssuntoId");

                    b.ToTable("Assuntos");
                });

            modelBuilder.Entity("BibliotecaDominio.ObjetosValor.Autor", b =>
                {
                    b.Property<int>("AutorId")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("NomeAutor");

                    b.HasKey("AutorId");

                    b.ToTable("Autores");
                });

            modelBuilder.Entity("BibliotecaDominio.ObjetosValor.CPF", b =>
                {
                    b.Property<string>("Cpf")
                        .ValueGeneratedOnAdd();

                    b.HasKey("Cpf");

                    b.ToTable("CPF");
                });

            modelBuilder.Entity("BibliotecaDominio.ObjetosValor.Classificacao", b =>
                {
                    b.Property<int>("ClassificacaoId")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("ClassificacaoObra");

                    b.HasKey("ClassificacaoId");

                    b.ToTable("Classificacoes");
                });

            modelBuilder.Entity("BibliotecaDominio.ObjetosValor.DadosLogin", b =>
                {
                    b.Property<int>("DadosLoginId")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.HasKey("DadosLoginId");

                    b.ToTable("DadosLogin");
                });

            modelBuilder.Entity("BibliotecaDominio.ObjetosValor.Editora", b =>
                {
                    b.Property<int>("EditoraId")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int?>("EnderecoId");

                    b.Property<string>("NomeEditora");

                    b.HasKey("EditoraId");

                    b.HasIndex("EnderecoId");

                    b.ToTable("Editoras");
                });

            modelBuilder.Entity("BibliotecaDominio.ObjetosValor.Estado", b =>
                {
                    b.Property<int>("EstadoId")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("NomeEstado");

                    b.Property<int?>("PaisId");

                    b.HasKey("EstadoId");

                    b.HasIndex("PaisId");

                    b.ToTable("Estados");
                });

            modelBuilder.Entity("BibliotecaDominio.ObjetosValor.Municipio", b =>
                {
                    b.Property<int>("MunicipioId")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int?>("EstadoId");

                    b.Property<string>("NomeMunicipio");

                    b.HasKey("MunicipioId");

                    b.HasIndex("EstadoId");

                    b.ToTable("Municipios");
                });

            modelBuilder.Entity("BibliotecaDominio.ObjetosValor.Pais", b =>
                {
                    b.Property<int>("PaisId")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("NomePais");

                    b.HasKey("PaisId");

                    b.ToTable("Paises");
                });

            modelBuilder.Entity("BibliotecaDominio.Entidades.Endereco", b =>
                {
                    b.HasOne("BibliotecaDominio.ObjetosValor.Municipio", "Municipio")
                        .WithMany("Enderecos")
                        .HasForeignKey("MunicipioId");
                });

            modelBuilder.Entity("BibliotecaDominio.Entidades.ExemplarLivro", b =>
                {
                    b.HasOne("BibliotecaDominio.Entidades.Livro", "Livro")
                        .WithMany("Exemplares")
                        .HasForeignKey("LivroId");
                });

            modelBuilder.Entity("BibliotecaDominio.Entidades.Livro", b =>
                {
                    b.HasOne("BibliotecaDominio.ObjetosValor.Assunto", "Assunto")
                        .WithMany("Livros")
                        .HasForeignKey("AssuntoId");

                    b.HasOne("BibliotecaDominio.ObjetosValor.Autor", "Autor")
                        .WithMany("Livros")
                        .HasForeignKey("AutorId");

                    b.HasOne("BibliotecaDominio.ObjetosValor.Classificacao", "Classificacao")
                        .WithMany("Livros")
                        .HasForeignKey("ClassificacaoId");

                    b.HasOne("BibliotecaDominio.ObjetosValor.Editora", "Editora")
                        .WithMany("Livros")
                        .HasForeignKey("EditoraId");
                });

            modelBuilder.Entity("BibliotecaDominio.Entidades.Pessoa", b =>
                {
                    b.HasOne("BibliotecaDominio.ObjetosValor.CPF", "CPF")
                        .WithMany()
                        .HasForeignKey("Cpf");

                    b.HasOne("BibliotecaDominio.Entidades.Endereco", "Endereco")
                        .WithMany("Pessoas")
                        .HasForeignKey("EnderecoId");

                    b.HasOne("BibliotecaDominio.ObjetosValor.DadosLogin", "Login")
                        .WithMany()
                        .HasForeignKey("LoginDadosLoginId");
                });

            modelBuilder.Entity("BibliotecaDominio.ObjetosValor.Editora", b =>
                {
                    b.HasOne("BibliotecaDominio.Entidades.Endereco", "Endereco")
                        .WithMany("Editoras")
                        .HasForeignKey("EnderecoId");
                });

            modelBuilder.Entity("BibliotecaDominio.ObjetosValor.Estado", b =>
                {
                    b.HasOne("BibliotecaDominio.ObjetosValor.Pais", "Pais")
                        .WithMany("Estados")
                        .HasForeignKey("PaisId");
                });

            modelBuilder.Entity("BibliotecaDominio.ObjetosValor.Municipio", b =>
                {
                    b.HasOne("BibliotecaDominio.ObjetosValor.Estado", "Estado")
                        .WithMany("Municipios")
                        .HasForeignKey("EstadoId");
                });
#pragma warning restore 612, 618
        }
    }
}
